### Authenticated API
GET http://localhost:3000/api/app
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTc4NDQyMzIsImV4cCI6MTU5Nzg0NDI5Mn0.08fd1baH5Zx24m3AxHwygc59i0M1f4ArjQCP8KXtLzA

### Login API
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username": "me@sandeep.com",
    "password": "sandeep"
}

### Register API
POST http://localhost:3000/api/user/signup
Content-Type: application/json

{
    "name": "sandeep",
    "email": "me@sandeep.com",
    "password":"sandeep"
}


###
POST http://localhost:3000/api/user/dummy

{

}

###
GET http://localhost:3001/api/app

###
GET http://localhost:3001/api/content/fetch